[package]
name = "clog"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
markdown = "1.0.0"

# Build all dependencies in release mode, even for dev builds.
# This should make debug builds faster.
[profile.dev.package."*"]
opt-level = 3
